import multer from "multer";
import {} from "dotenv/config";

// Get max file size from environment variable or use default (10MB)
const getMaxFileSize = () => {
  const envMaxSize = process.env.MAX_FILE_SIZE;
  if (envMaxSize) {
    const parsed = parseInt(envMaxSize, 10);
    return isNaN(parsed) ? 10 * 1024 * 1024 : parsed;
  }
  return 10 * 1024 * 1024; // 10MB default
};

// Use memory storage instead of disk storage for serverless compatibility
const storage = multer.memoryStorage();

// File filter to only allow PDF files
const fileFilter = (req, file, cb) => {
  if (file.mimetype === "application/pdf") {
    cb(null, true);
  } else {
    cb(new Error("Only PDF files are allowed"), false);
  }
};

// Configure multer with memory storage
const upload = multer({
  storage: storage,
  fileFilter: fileFilter,
  limits: {
    fileSize: getMaxFileSize(),
  },
});

// Middleware for single file upload
export const uploadMedicalReport = upload.single("medicalReport");

// Validation middleware
export const validateMedicalReport = (req, res, next) => {
  if (!req.file) {
    return res.status(400).json({
      success: false,
      message: "Medical report PDF file is required",
    });
  }

  // Additional validation for medical content
  const filename = req.file.originalname.toLowerCase();
  const medicalKeywords = [
    "blood",
    "lab",
    "laboratory",
    "test",
    "report",
    "medical",
    "health",
    "diagnosis",
    "cbc",
    "liver",
    "kidney",
    "glucose",
    "cholesterol",
    "protein",
    "hemoglobin",
    "platelet",
    "white blood",
    "red blood",
    "urine",
    "stool",
    "pathology",
    "radiology",
    "scan",
    "xray",
    "x-ray",
    "mri",
    "ct",
    "ultrasound",
    "ecg",
    "ekg",
    "prescription",
    "discharge",
    "summary",
    "results",
    "findings",
    "examination",
    "consultation",
    "clinic",
    "hospital",
    "doctor",
    "physician",
    "patient",
    "treatment",
    "therapy",
    "medication",
    "drug",
    "allergy",
    "vaccination",
    "immunization",
    "screening",
    "checkup",
    "check-up",
    "visit",
    "appointment",
    "record",
    "history",
    "chart",
    "notes",
    "assessment",
    "evaluation",
    "analysis",
    "study",
    "research",
    "clinical",
    "biopsy",
    "culture",
    "specimen",
    "sample",
    "vital",
    "signs",
    "pressure",
    "temperature",
    "pulse",
    "respiratory",
    "cardiac",
    "pulmonary",
    "neurological",
    "dermatological",
    "ophthalmological",
    "gynecological",
    "urological",
    "orthopedic",
    "psychiatric",
    "psychological",
    "therapeutic",
    "rehabilitation",
    "physical",
    "mental",
    "behavioral",
    "cognitive",
    "developmental",
    "pediatric",
    "geriatric",
    "oncology",
    "cardiology",
    "neurology",
    "dermatology",
    "ophthalmology",
    "gynecology",
    "urology",
    "orthopedics",
    "psychiatry",
    "psychology",
    "therapy",
    "rehab",
    "physio",
    "occupational",
    "speech",
    "language",
    "hearing",
    "vision",
    "dental",
    "oral",
    "maxillofacial",
    "plastic",
    "cosmetic",
    "reconstructive",
    "surgical",
    "procedure",
    "operation",
    "intervention",
    "treatment",
    "care",
    "management",
    "plan",
    "protocol",
    "guideline",
    "recommendation",
    "advice",
    "instruction",
    "education",
    "counseling",
    "support",
    "service",
    "facility",
    "center",
    "department",
    "unit",
    "ward",
    "room",
    "bed",
    "admission",
    "discharge",
    "transfer",
    "referral",
    "consultation",
    "follow-up",
    "followup",
    "monitoring",
    "surveillance",
    "prevention",
    "screening",
    "detection",
    "diagnosis",
    "prognosis",
    "outcome",
    "result",
    "finding",
    "conclusion",
    "recommendation",
    "action",
    "plan",
    "goal",
    "objective",
    "target",
    "indicator",
    "measure",
    "metric",
    "score",
    "rating",
    "grade",
    "level",
    "status",
    "condition",
    "state",
    "phase",
    "stage",
    "progression",
    "regression",
    "improvement",
    "deterioration",
    "stability",
    "change",
    "response",
    "reaction",
    "side effect",
    "adverse",
    "complication",
    "risk",
    "factor",
    "indicator",
    "marker",
    "biomarker",
    "parameter",
    "variable",
    "value",
    "range",
    "normal",
    "abnormal",
    "elevated",
    "reduced",
    "increased",
    "decreased",
    "high",
    "low",
    "positive",
    "negative",
    "present",
    "absent",
    "detected",
    "undetected",
    "found",
    "not found",
    "identified",
    "unidentified",
    "confirmed",
    "unconfirmed",
    "verified",
    "unverified",
    "validated",
    "invalidated",
    "approved",
    "rejected",
    "accepted",
    "declined",
    "recommended",
    "not recommended",
    "indicated",
    "contraindicated",
    "suitable",
    "unsuitable",
    "appropriate",
    "inappropriate",
    "safe",
    "unsafe",
    "effective",
    "ineffective",
    "beneficial",
    "harmful",
    "therapeutic",
    "non-therapeutic",
    "curative",
    "palliative",
    "preventive",
    "prophylactic",
    "diagnostic",
    "prognostic",
    "predictive",
    "descriptive",
    "analytical",
    "comparative",
    "longitudinal",
    "cross-sectional",
    "retrospective",
    "prospective",
    "randomized",
    "controlled",
    "placebo",
    "double-blind",
    "single-blind",
    "open-label",
    "crossover",
    "parallel",
    "factorial",
    "adaptive",
    "sequential",
    "group",
    "individual",
    "population",
    "sample",
    "cohort",
    "case",
    "control",
    "trial",
    "study",
    "experiment",
    "investigation",
    "research",
    "analysis",
    "evaluation",
    "assessment",
    "measurement",
    "observation",
    "monitoring",
    "surveillance",
    "tracking",
    "follow-up",
    "followup",
    "outcome",
    "endpoint",
    "primary",
    "secondary",
    "tertiary",
    "surrogate",
    "intermediate",
    "final",
    "ultimate",
    "clinical",
    "biological",
    "pharmacological",
    "pharmacokinetic",
    "pharmacodynamic",
    "toxicological",
    "immunological",
    "genetic",
    "genomic",
    "proteomic",
    "metabolomic",
    "transcriptomic",
    "epigenomic",
    "microbiomic",
    "viromic",
    "bacteriomic",
    "fungomic",
    "parasitomic",
    "pathogenic",
    "non-pathogenic",
    "infectious",
    "non-infectious",
    "contagious",
    "non-contagious",
    "transmissible",
    "non-transmissible",
    "communicable",
    "non-communicable",
    "acute",
    "chronic",
    "subacute",
    "fulminant",
    "progressive",
    "regressive",
    "stable",
    "unstable",
    "recurrent",
    "remitting",
    "relapsing",
    "intermittent",
    "continuous",
    "persistent",
    "transient",
    "temporary",
    "permanent",
    "reversible",
    "irreversible",
    "curable",
    "incurable",
    "treatable",
    "untreatable",
    "manageable",
    "unmanageable",
    "controllable",
    "uncontrollable",
    "preventable",
    "unpreventable",
    "avoidable",
    "unavoidable",
    "modifiable",
    "non-modifiable",
    "reversible",
    "irreversible",
    "temporary",
    "permanent",
    "acute",
    "chronic",
    "subacute",
    "fulminant",
    "progressive",
    "regressive",
    "stable",
    "unstable",
    "recurrent",
    "remitting",
    "relapsing",
    "intermittent",
    "continuous",
    "persistent",
    "transient",
    "temporary",
    "permanent",
    "reversible",
    "irreversible",
    "curable",
    "incurable",
    "treatable",
    "untreatable",
    "manageable",
    "unmanageable",
    "controllable",
    "uncontrollable",
    "preventable",
    "unpreventable",
    "avoidable",
    "unavoidable",
    "modifiable",
    "non-modifiable",
  ];

  const hasMedicalContent = medicalKeywords.some((keyword) =>
    filename.includes(keyword)
  );

  // Content-based validation is done in the controller after PDF processing
  next();
};

// Error handling middleware for multer
export const handleUploadError = (error, req, res, next) => {
  if (error instanceof multer.MulterError) {
    if (error.code === "LIMIT_FILE_SIZE") {
      return res.status(400).json({
        success: false,
        message: "File size too large. Maximum size is 10MB.",
      });
    }
    if (error.code === "LIMIT_UNEXPECTED_FILE") {
      return res.status(400).json({
        success: false,
        message:
          "Unexpected field name. Use 'medicalReport' as the field name.",
      });
    }
  }

  if (error.message === "Only PDF files are allowed") {
    return res.status(400).json({
      success: false,
      message: "Only PDF files are allowed for medical reports.",
    });
  }

  return res.status(500).json({
    success: false,
    message: "File upload error: " + error.message,
  });
};
